// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

import 'package:flutter/foundation.dart';

@immutable
class RegisterDto {
  const RegisterDto({
    required this.name,
    required this.email,
    required this.password,
  });

  final String name;
  final String email;
  final String password;

  RegisterDto copyWith({
    String? name,
    String? email,
    String? password,
  }) {
    return RegisterDto(
      name: name ?? this.name,
      email: email ?? this.email,
      password: password ?? this.password,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'email': email,
      'password': password,
    };
  }

  factory RegisterDto.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return RegisterDto(
      name: cast<String>('name'),
      email: cast<String>('email'),
      password: cast<String>('password'),
    );
  }

  String toJson() => json.encode(toMap());

  factory RegisterDto.fromJson(String source) =>
      RegisterDto.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() =>
      'RegisterUserDto(name: $name, email: $email, password: $password)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is RegisterDto &&
        other.name == name &&
        other.email == email &&
        other.password == password;
  }

  @override
  int get hashCode => name.hashCode ^ email.hashCode ^ password.hashCode;
}
