// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

import 'package:flutter/foundation.dart';

import '../../pix/models/pix_key_model.dart';

// "account2": {
//     "bankNumber": 0,
//     "agencyNumber": 0,
//     "accountNumber": "string",
//     "cpf": "string",
//     "pixKeys": [
//       {
//         "key": "string",
//         "type": 0
//       }
//     ]
//   },

class AccountModel {
  final int bankNumber;
  final int agencyNumber;
  final String accountNumber;
  final String cpf;
  final List<PixKeyModel> pixKeys;
  const AccountModel({
    this.bankNumber = 0,
    this.agencyNumber = 0,
    this.accountNumber = '',
    this.cpf = '',
    this.pixKeys = const [],
  });

  AccountModel copyWith({
    int? bankNumber,
    int? agencyNumber,
    String? accountNumber,
    String? cpf,
    List<PixKeyModel>? pixKeys,
  }) {
    return AccountModel(
      bankNumber: bankNumber ?? this.bankNumber,
      agencyNumber: agencyNumber ?? this.agencyNumber,
      accountNumber: accountNumber ?? this.accountNumber,
      cpf: cpf ?? this.cpf,
      pixKeys: pixKeys ?? this.pixKeys,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'bankNumber': bankNumber,
      'agencyNumber': agencyNumber,
      'accountNumber': accountNumber,
      'cpf': cpf,
      'pixKeys': pixKeys.map((x) => x.toMap()).toList(),
    };
  }

  factory AccountModel.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return AccountModel(
      bankNumber: cast<num>('bankNumber').toInt(),
      agencyNumber: cast<num>('agencyNumber').toInt(),
      accountNumber: cast<String>('accountNumber'),
      cpf: cast<String>('cpf'),
      pixKeys: List<PixKeyModel>.from(cast<Iterable>('pixKeys')
          .map((x) => PixKeyModel.fromMap(Map.from(x as Map)))),
    );
  }

  String toJson() => json.encode(toMap());

  factory AccountModel.fromJson(String source) =>
      AccountModel.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return 'AccountModel(bankNumber: $bankNumber, agencyNumber: $agencyNumber, accountNumber: $accountNumber, cpf: $cpf, pixKeys: $pixKeys)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is AccountModel &&
        other.bankNumber == bankNumber &&
        other.agencyNumber == agencyNumber &&
        other.accountNumber == accountNumber &&
        other.cpf == cpf &&
        listEquals(other.pixKeys, pixKeys);
  }

  @override
  int get hashCode {
    return bankNumber.hashCode ^
        agencyNumber.hashCode ^
        accountNumber.hashCode ^
        cpf.hashCode ^
        pixKeys.hashCode;
  }
}
