// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

class AuthenticateModel {
  final String originalTransactionId;
  final int agencyNumber;
  final String accountNumber;
  final String cardPassword;
  const AuthenticateModel({
    this.originalTransactionId = '',
    this.agencyNumber = 0,
    this.accountNumber = '',
    this.cardPassword = '',
  });

  AuthenticateModel copyWith({
    String? originalTransactionId,
    int? agencyNumber,
    String? accountNumber,
    String? cardPassword,
  }) {
    return AuthenticateModel(
      originalTransactionId:
          originalTransactionId ?? this.originalTransactionId,
      agencyNumber: agencyNumber ?? this.agencyNumber,
      accountNumber: accountNumber ?? this.accountNumber,
      cardPassword: cardPassword ?? this.cardPassword,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'originalTransactionId': originalTransactionId,
      'agencyNumber': agencyNumber,
      'accountNumber': accountNumber,
      'cardPassword': cardPassword,
    };
  }

  factory AuthenticateModel.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return AuthenticateModel(
      originalTransactionId: cast<String>('originalTransactionId'),
      agencyNumber: cast<num>('agencyNumber').toInt(),
      accountNumber: cast<String>('accountNumber'),
      cardPassword: cast<String>('cardPassword'),
    );
  }

  String toJson() => json.encode(toMap());

  factory AuthenticateModel.fromJson(String source) =>
      AuthenticateModel.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return 'AuthenticatedTransactionModel(originalTransactionId: $originalTransactionId, agencyNumber: $agencyNumber, accountNumber: $accountNumber, cardPassword: $cardPassword)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is AuthenticateModel &&
        other.originalTransactionId == originalTransactionId &&
        other.agencyNumber == agencyNumber &&
        other.accountNumber == accountNumber &&
        other.cardPassword == cardPassword;
  }

  @override
  int get hashCode {
    return originalTransactionId.hashCode ^
        agencyNumber.hashCode ^
        accountNumber.hashCode ^
        cardPassword.hashCode;
  }
}
