// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

class BalanceModel {
  final int agencyNumber;
  final String accountNumber;
  final String cpf;
  final String name;
  final double balance;
  final String formattedBalance;
  final DateTime lastUpdate;
  final String correlationId;
  const BalanceModel({
    this.agencyNumber = 0,
    this.accountNumber = '',
    this.cpf = '',
    this.name = '',
    this.balance = 0.0,
    this.formattedBalance = '',
    required this.lastUpdate,
    this.correlationId = '',
  });

  BalanceModel copyWith({
    int? agencyNumber,
    String? accountNumber,
    String? cpf,
    String? name,
    double? balance,
    String? formattedBalance,
    DateTime? lastUpdate,
    String? correlationId,
  }) {
    return BalanceModel(
      agencyNumber: agencyNumber ?? this.agencyNumber,
      accountNumber: accountNumber ?? this.accountNumber,
      cpf: cpf ?? this.cpf,
      name: name ?? this.name,
      balance: balance ?? this.balance,
      formattedBalance: formattedBalance ?? this.formattedBalance,
      lastUpdate: lastUpdate ?? this.lastUpdate,
      correlationId: correlationId ?? this.correlationId,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'agencyNumber': agencyNumber,
      'accountNumber': accountNumber,
      'cpf': cpf,
      'name': name,
      'balance': balance,
      'formattedBalance': formattedBalance,
      'lastUpdate': lastUpdate.toUtc().toIso8601String(),
      'correlationId': correlationId,
    };
  }

  factory BalanceModel.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return BalanceModel(
      agencyNumber: cast<num>('agencyNumber').toInt(),
      accountNumber: cast<String>('accountNumber'),
      cpf: cast<String>('cpf'),
      name: cast<String>('name'),
      balance: cast<num>('balance').toDouble(),
      formattedBalance: cast<String>('formattedBalance'),
      lastUpdate: DateTime.parse(cast<String>('lastUpdate')),
      correlationId: cast<String>('correlationId'),
    );
  }

  String toJson() => json.encode(toMap());

  factory BalanceModel.fromJson(String source) =>
      BalanceModel.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return 'AccountBalanceModel(agencyNumber: $agencyNumber, accountNumber: $accountNumber, cpf: $cpf, name: $name, balance: $balance, formattedBalance: $formattedBalance, lastUpdate: $lastUpdate, correlationId: $correlationId)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is BalanceModel &&
        other.agencyNumber == agencyNumber &&
        other.accountNumber == accountNumber &&
        other.cpf == cpf &&
        other.name == name &&
        other.balance == balance &&
        other.formattedBalance == formattedBalance &&
        other.lastUpdate == lastUpdate &&
        other.correlationId == correlationId;
  }

  @override
  int get hashCode {
    return agencyNumber.hashCode ^
        accountNumber.hashCode ^
        cpf.hashCode ^
        name.hashCode ^
        balance.hashCode ^
        formattedBalance.hashCode ^
        lastUpdate.hashCode ^
        correlationId.hashCode;
  }
}
